apiVersion: v1
kind: Service
metadata:
  name: nfd-master
  namespace: openshift-nfd
spec:
  type: ClusterIP
  selector:
    app: nfd-master
  ports:
  - protocol: TCP
    port: 12000
    targetPort: 12000
    name: nfd

