// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controllers/nodefeaturerule_reconciler.go
//
// Generated by this command:
//
//	mockgen -source=internal/controllers/nodefeaturerule_reconciler.go -package=new_controllers -destination=internal/controllers/mock_nodefeaturerule_reconciler.go nodeFeatureRuleHelperAPI
//
// Package new_controllers is a generated GoMock package.
package new_controllers
