// Code generated by MockGen. DO NOT EDIT.
// Source: networkpolicy.go
//
// Generated by this command:
//
//	mockgen -source=networkpolicy.go -package=networkpolicy -destination=mock_networkpolicy.go NetworkPolicyAPI
//

// Package networkpolicy is a generated GoMock package.
package networkpolicy

import (
	context "context"
	reflect "reflect"

	v1 "github.com/openshift/cluster-nfd-operator/api/v1"
	gomock "go.uber.org/mock/gomock"
	networkingv1 "k8s.io/api/networking/v1"
)

// MockNetworkPolicyAPI is a mock of NetworkPolicyAPI interface.
type MockNetworkPolicyAPI struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkPolicyAPIMockRecorder
	isgomock struct{}
}

// MockNetworkPolicyAPIMockRecorder is the mock recorder for MockNetworkPolicyAPI.
type MockNetworkPolicyAPIMockRecorder struct {
	mock *MockNetworkPolicyAPI
}

// NewMockNetworkPolicyAPI creates a new mock instance.
func NewMockNetworkPolicyAPI(ctrl *gomock.Controller) *MockNetworkPolicyAPI {
	mock := &MockNetworkPolicyAPI{ctrl: ctrl}
	mock.recorder = &MockNetworkPolicyAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkPolicyAPI) EXPECT() *MockNetworkPolicyAPIMockRecorder {
	return m.recorder
}

// DeleteNetworkPolicy mocks base method.
func (m *MockNetworkPolicyAPI) DeleteNetworkPolicy(ctx context.Context, namespace, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetworkPolicy", ctx, namespace, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetworkPolicy indicates an expected call of DeleteNetworkPolicy.
func (mr *MockNetworkPolicyAPIMockRecorder) DeleteNetworkPolicy(ctx, namespace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetworkPolicy", reflect.TypeOf((*MockNetworkPolicyAPI)(nil).DeleteNetworkPolicy), ctx, namespace, name)
}

// SetGCNetworkPolicyAsDesired mocks base method.
func (m *MockNetworkPolicyAPI) SetGCNetworkPolicyAsDesired(nfdInstance *v1.NodeFeatureDiscovery, np *networkingv1.NetworkPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGCNetworkPolicyAsDesired", nfdInstance, np)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGCNetworkPolicyAsDesired indicates an expected call of SetGCNetworkPolicyAsDesired.
func (mr *MockNetworkPolicyAPIMockRecorder) SetGCNetworkPolicyAsDesired(nfdInstance, np any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGCNetworkPolicyAsDesired", reflect.TypeOf((*MockNetworkPolicyAPI)(nil).SetGCNetworkPolicyAsDesired), nfdInstance, np)
}

// SetMasterNetworkPolicyAsDesired mocks base method.
func (m *MockNetworkPolicyAPI) SetMasterNetworkPolicyAsDesired(nfdInstance *v1.NodeFeatureDiscovery, np *networkingv1.NetworkPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMasterNetworkPolicyAsDesired", nfdInstance, np)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMasterNetworkPolicyAsDesired indicates an expected call of SetMasterNetworkPolicyAsDesired.
func (mr *MockNetworkPolicyAPIMockRecorder) SetMasterNetworkPolicyAsDesired(nfdInstance, np any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMasterNetworkPolicyAsDesired", reflect.TypeOf((*MockNetworkPolicyAPI)(nil).SetMasterNetworkPolicyAsDesired), nfdInstance, np)
}

// SetWorkerNetworkPolicyAsDesired mocks base method.
func (m *MockNetworkPolicyAPI) SetWorkerNetworkPolicyAsDesired(nfdInstance *v1.NodeFeatureDiscovery, np *networkingv1.NetworkPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkerNetworkPolicyAsDesired", nfdInstance, np)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkerNetworkPolicyAsDesired indicates an expected call of SetWorkerNetworkPolicyAsDesired.
func (mr *MockNetworkPolicyAPIMockRecorder) SetWorkerNetworkPolicyAsDesired(nfdInstance, np any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkerNetworkPolicyAsDesired", reflect.TypeOf((*MockNetworkPolicyAPI)(nil).SetWorkerNetworkPolicyAsDesired), nfdInstance, np)
}
