apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: nfd-prune
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfd-prune
subjects:
- kind: ServiceAccount
  name: nfd-prune
  namespace: openshift-nfd
